name: Windows

on: [push, pull_request]

jobs:
  build:
    name: MSVC

    runs-on: 'windows-latest'
    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: mamba-org/setup-micromamba@v1
      with:
        init-shell: bash
        environment-file: ci/environment.yml
        environment-name: "pdal-build"
        cache-environment: true
        cache-downloads: true

    - name: Setup
      shell: bash -l {0}
      run: |
          mkdir build
          source ./ci/win/setup.sh

    - name: CMake
      shell: bash -l {0}
      working-directory: ./build
      run: |
          source ../ci/win/cmake.sh

    - name: Compile
      shell: bash -l {0}
      working-directory: ./build
      run: |
          source ../ci/win/compile.sh

    - name: Test
      shell: bash -l {0}
      working-directory: ./build
      run: |
          source ../ci/win/test.sh

